# Generated by Django 4.2.7 on 2025-10-27 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipleship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed')], default='completed', max_length=20)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipleship.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'level'], name='progress_le_user_id_4a176c_idx')],
                'unique_together': {('user', 'level')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipleship.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lesson'], name='progress_le_user_id_8c8ec5_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
