# Generated by Django 4.2.7 on 2025-11-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipleship', '0002_discipleshiplesson_discipleshiplevel_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-completed_at', '-created_at'], 'verbose_name': 'Lesson Progress', 'verbose_name_plural': 'Lesson Progress'},
        ),
        migrations.AlterModelOptions(
            name='levelprogress',
            options={'ordering': ['-completed_at', '-created_at'], 'verbose_name': 'Level Progress', 'verbose_name_plural': 'Level Progress'},
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress_entries', to='discipleship.discipleshiplesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='levelprogress',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress_entries', to='discipleship.discipleshiplevel'),
        ),
        migrations.AlterField(
            model_name='levelprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'status'], name='progress_le_user_id_2913b9_idx'),
        ),
    ]
