# Generated by Django 4.2.7 on 2025-09-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lesson',
            new_name='content_les_series__e81338_idx',
            old_name='content_les_series__7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='content_pos_status_90c640_idx',
            old_name='content_pos_status_4f7c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='content_pos_categor_cf4953_idx',
            old_name='content_pos_categor_8c5c4a_idx',
        ),
    ]
