# Generated by Django 4.2.7 on 2025-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_announcement_lessoncomment_lessonlike_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GOD CARES 365', max_length=100)),
                ('from_email', models.EmailField(default='no-reply@example.com', max_length=254)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('footer_team', models.TextField(blank=True, help_text='Orodha/maelezo mafupi ya timu')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
