# Generated by Django 4.2.7 on 2025-10-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GOD CARES 365', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('footer_about', models.TextField(blank=True, default='Tovuti hii imeundwa kukuimarisha katika imani, kukuunga mkono katika maombi, na kukupeleka karibu na Mungu.')),
                ('email_from_name', models.CharField(default='GOD CARES 365', max_length=120)),
                ('email_from_address', models.EmailField(default='fathercares365@gmail.com', max_length=254)),
                ('notifications_opt_in_default', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
