# Generated by Django 4.2.7 on 2025-11-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_sitesetting_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('seeker', '📘 Discover Truth - God Cares 365 Student'), ('scholar', '📖 Understand Prophecy - God Cares 365 Prophecy Student'), ('missionary', '🌍 Live & Share Message - God Cares 365 Missionary')], default='seeker', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('seeker_completed', models.BooleanField(default=False)),
                ('scholar_completed', models.BooleanField(default=False)),
                ('missionary_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discipleship Journey',
                'verbose_name_plural': 'Discipleship Journeys',
            },
        ),
        migrations.CreateModel(
            name='GlobalSoulsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_souls_reached', models.BigIntegerField(default=0)),
                ('total_baptisms', models.IntegerField(default=0)),
                ('total_mission_reports', models.IntegerField(default=0)),
                ('total_bible_study_groups', models.IntegerField(default=0)),
                ('active_missionaries', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Souls Counter',
                'verbose_name_plural': 'Global Souls Counter',
            },
        ),
        migrations.CreateModel(
            name='MissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('gps_coordinates', models.JSONField(default=dict)),
                ('date_conducted', models.DateTimeField(default=django.utils.timezone.now)),
                ('souls_reached', models.IntegerField(default=0)),
                ('testimonies', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('baptisms_performed', models.IntegerField(default=0)),
                ('baptism_details', models.JSONField(default=list)),
                ('photos', models.JSONField(default=list)),
                ('videos', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_conducted'],
            },
        ),
        migrations.CreateModel(
            name='MissionMapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('gps_coordinates', models.JSONField(default=dict)),
                ('date_visited', models.DateTimeField()),
                ('visit_type', models.CharField(choices=[('door_to_door', 'Door-to-Door Evangelism'), ('bible_study', 'Bible Study Group'), ('community', 'Community Outreach'), ('follow_up', 'Follow-up Visit'), ('baptism', 'Baptism Ceremony')], max_length=50)),
                ('souls_contacted', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('photos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_visited'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('seeker_completion', '📘 Faith Discovery Badge - Seeker Stage'), ('scholar_completion', '📖 Prophetic Insights Award - Scholar Stage'), ('missionary_license', '🌍 Certified Missionary License - Missionary Stage'), ('bible_study_leader', '👥 Bible Study Group Leader'), ('evangelism', '🔥 Evangelism Certificate')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/')),
                ('pdf_certificate', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('meeting_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('meeting_schedule', models.JSONField(default=dict)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('online_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_members_count', models.IntegerField(default=1)),
                ('max_members', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.lesson')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
                ('lessons_completed', models.ManyToManyField(blank=True, related_name='completed_in_groups', to='content.lesson')),
                ('members', models.ManyToManyField(blank=True, related_name='study_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaptismRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_age', models.IntegerField(blank=True, null=True)),
                ('candidate_contact', models.CharField(blank=True, max_length=100)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('baptism_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('baptism_notes', models.TextField(blank=True)),
                ('previous_religion', models.CharField(blank=True, max_length=100)),
                ('testimony', models.TextField(blank=True)),
                ('follow_up_plan', models.TextField(blank=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptisms_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-baptism_date'],
            },
        ),
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('seeker', '📘 Discover Truth - God Cares 365 Student'), ('scholar', '📖 Understand Prophecy - God Cares 365 Prophecy Student'), ('missionary', '🌍 Live & Share Message - God Cares 365 Missionary')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='content.discipleshipjourney')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='content.lesson')),
            ],
            options={
                'verbose_name_plural': 'Stage Progress',
                'unique_together': {('journey', 'lesson')},
            },
        ),
    ]
