# Generated by Django 4.2.7 on 2025-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipleship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='discipleship/lessons/pdfs/')),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('bible_references', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points_value', models.PositiveIntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
                ('requires_previous', models.BooleanField(default=True, help_text='Kama true, lazima previous lesson iwe completed kabla ya hii.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discipleship Lesson',
                'verbose_name_plural': 'Discipleship Lessons',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DiscipleshipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_score', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Discipleship Level',
                'verbose_name_plural': 'Discipleship Levels',
                'ordering': ['path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DiscipleshipPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('seeker', '📘 Discover Truth - God Cares 365 Student'), ('scholar', '📖 Understand Prophecy - God Cares 365 Prophecy Student'), ('missionary', '🌍 Live & Share Message - God Cares 365 Missionary')], max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='discipleship/paths/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Discipleship Path',
                'verbose_name_plural': 'Discipleship Paths',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Path Enrollment',
                'verbose_name_plural': 'Path Enrollments',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.PositiveIntegerField(default=70)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quiz Choice',
                'verbose_name_plural': 'Quiz Choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
    ]
