# Generated by Django 4.2.7 on 2025-11-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_lessonprogress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipleship', '0002_discipleshiplesson_discipleshiplevel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='discipleship.quiz'),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='discipleship.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='discipleship.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='discipleship.discipleshiplesson'),
        ),
        migrations.AddField(
            model_name='pathenrollment',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discipleship.discipleshiplevel'),
        ),
        migrations.AddField(
            model_name='pathenrollment',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='discipleship.discipleshippath'),
        ),
        migrations.AddField(
            model_name='pathenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='discipleship.discipleshiplesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipleship_lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discipleshippath',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='discipleship.discipleshippath'),
        ),
        migrations.AddField(
            model_name='discipleshiplevel',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='discipleship.discipleshippath'),
        ),
        migrations.AddField(
            model_name='discipleshiplesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='discipleship.discipleshiplevel'),
        ),
        migrations.AddIndex(
            model_name='pathenrollment',
            index=models.Index(fields=['user', 'is_active'], name='discipleshi_user_id_7f91c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pathenrollment',
            unique_together={('user', 'path')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'status'], name='discipleshi_user_id_189c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'status'], name='discipleshi_lesson__c46059_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='discipleshiplevel',
            unique_together={('path', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='discipleshiplesson',
            unique_together={('level', 'slug')},
        ),
    ]
